#!/bin/bash
if ! (which python3 >/dev/null && python3 --version | grep ' 3.' >/dev/null); then
  echo "You must have python 3 installed to run this."
  exit 1
fi

chromium-browser "--user-data-dir=$(realpath $PWD)/.chromium-browser" --new-window "https://github.com/pflagerd/fastapi-template" "http://127.0.0.1:8000" "http://127.0.0.1:8000/docs" "http://127.0.0.1:8000/redoc" "http://127.0.0.1:8000/openapi.json" &
python3 $(dirname "$(readlink -f "$0")")/runme.py
